import dynamic from 'next/dynamic';

export const components = {
  Background: dynamic(() => import('./Background')),
  BannerVideo: dynamic(() => import('./BannerVideo')),
  Button: dynamic(() => import('./Button')),
  Description: dynamic(() => import('./Description')),
  Pagination: dynamic(() => import('./Pagination')),
  Icon: dynamic(() => import('./Icon')),
  Image: dynamic(() => import('./Image')),
  Link: dynamic(() => import('./Link')),
  Text: dynamic(() => import('./Text')),
  TitleComplex: dynamic(() => import('./TitleComplex')),
  TitleHeader: dynamic(() => import('./TitleHeader')),
  TitleHeaderGradient: dynamic(() => import('./TitleHeaderGradient')),
  InputText: dynamic(() => import('./InputText')),
  Navigation: dynamic(() => import('./Navigation')),
  Dropdown: dynamic(() => import('./Dropdown')),
  Collapse: dynamic(() => import('./Collapse')),
  CustomWidgete920019b2412: dynamic(() => import('./CustomWidgete920019b2412')),
  AppleHeader: dynamic(() => import("./AppleHeader")),  CapabilityData: dynamic(() => import("./CapabilityData")),
  AppleNavigation: dynamic(() => import("./AppleNavigation")),
  CustomWidgetc56a11e672eb: dynamic(() => import("./CustomWidgetc56a11e672eb")),
  CustomWidget88226bf4ff8c: dynamic(() => import("./CustomWidget88226bf4ff8c")),
};
